run:
  timeout: 5m
  tests: true
  build-tags: []

  skip-dirs:
    - vendor

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosec
    - gofmt
    - goimports
    - misspell
    - revive

linters-settings:
  errcheck:
    check-type-assertions: true
  goimports:
    local-prefixes: github.com/guillermoballester/propagatorGo
  govet:
    check-shadowing: true
  revive:
    confidence: 0.8
  unused:
    check-exported: false

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
  # Maximum issues count per one linter
  max-issues-per-linter: 0
  # Maximum count of issues with the same text
  max-same-issues: 0