
version: '3.8'

services:
  propagator:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: propagatorGo
    restart: "no"  # For easier debugging
    environment:
      - TZ=UTC
    volumes:
      - ./config.json:/app/config.json
    depends_on:
      - redis
    networks:
      - propagatorGo-network

  redis:
    image: redis:6-alpine
    container_name: propagatorGo-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - propagatorGo-network

  postgres:
    image: postgres:15-alpine
    container_name: propagatorGo-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=propagatorGo
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d  # Mount migrations directory
    networks:
      - propagatorGo-network


volumes:
  redis-data:
  postgres-data:

networks:
  propagatorGo-network:
    driver: bridge