// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.createArticleStmt, err = db.PrepareContext(ctx, createArticle); err != nil {
		return nil, fmt.Errorf("error preparing query CreateArticle: %w", err)
	}
	if q.getArticleStmt, err = db.PrepareContext(ctx, getArticle); err != nil {
		return nil, fmt.Errorf("error preparing query GetArticle: %w", err)
	}
	if q.getArticleBySiteStmt, err = db.PrepareContext(ctx, getArticleBySite); err != nil {
		return nil, fmt.Errorf("error preparing query GetArticleBySite: %w", err)
	}
	if q.getArticleBySymbolStmt, err = db.PrepareContext(ctx, getArticleBySymbol); err != nil {
		return nil, fmt.Errorf("error preparing query GetArticleBySymbol: %w", err)
	}
	if q.getArticleByURLStmt, err = db.PrepareContext(ctx, getArticleByURL); err != nil {
		return nil, fmt.Errorf("error preparing query GetArticleByURL: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.createArticleStmt != nil {
		if cerr := q.createArticleStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createArticleStmt: %w", cerr)
		}
	}
	if q.getArticleStmt != nil {
		if cerr := q.getArticleStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getArticleStmt: %w", cerr)
		}
	}
	if q.getArticleBySiteStmt != nil {
		if cerr := q.getArticleBySiteStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getArticleBySiteStmt: %w", cerr)
		}
	}
	if q.getArticleBySymbolStmt != nil {
		if cerr := q.getArticleBySymbolStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getArticleBySymbolStmt: %w", cerr)
		}
	}
	if q.getArticleByURLStmt != nil {
		if cerr := q.getArticleByURLStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getArticleByURLStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                     DBTX
	tx                     *sql.Tx
	createArticleStmt      *sql.Stmt
	getArticleStmt         *sql.Stmt
	getArticleBySiteStmt   *sql.Stmt
	getArticleBySymbolStmt *sql.Stmt
	getArticleByURLStmt    *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                     tx,
		tx:                     tx,
		createArticleStmt:      q.createArticleStmt,
		getArticleStmt:         q.getArticleStmt,
		getArticleBySiteStmt:   q.getArticleBySiteStmt,
		getArticleBySymbolStmt: q.getArticleBySymbolStmt,
		getArticleByURLStmt:    q.getArticleByURLStmt,
	}
}
