// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"database/sql"
	"time"
)

type Article struct {
	ID        int32          `json:"id"`
	Title     string         `json:"title"`
	Url       string         `json:"url"`
	Text      sql.NullString `json:"text"`
	SiteName  string         `json:"site_name"`
	ScrapedAt time.Time      `json:"scraped_at"`
	CreatedAt time.Time      `json:"created_at"`
	Symbol    string         `json:"symbol"`
}
