// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"context"
)

type Querier interface {
	CreateArticle(ctx context.Context, arg CreateArticleParams) (Article, error)
	GetArticle(ctx context.Context, id int32) (Article, error)
	GetArticleBySite(ctx context.Context, siteName string) ([]Article, error)
	GetArticleBySymbol(ctx context.Context, symbol string) ([]Article, error)
	GetArticleByURL(ctx context.Context, url string) (Article, error)
}

var _ Querier = (*Queries)(nil)
